apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-cleaner-listener
  namespace: ntbs-build
spec:
  serviceAccountName: tekton-cleaner
  triggers:
    - name: cleanup-pipelineruns-and-taskruns
      template:
        name: cleanup-runs
