# To be deployed on PHE Kubernetes and run against databases on the "dev" box DEVCOL01
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntbs-dev
  template:
    metadata:
      labels:
        app: ntbs-dev
    spec:
      containers:
        - name: ntbs-dev
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:dev"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: reporting
            - name: Hangfire__WorkerCount
              value: "3"
            - name: ExternalLinks__ReportingOverview
              value: "https://app.powerbi.com/Redirect?action=OpenApp&appId=5ae64787-d2aa-4beb-8bf8-18340efe12ab&ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666"
            - name: ExternalLinks__ClusterReport
              value: "https://app.powerbi.com/groups/me/apps/5ae64787-d2aa-4beb-8bf8-18340efe12ab/reports/7b0921bd-8e4b-46f3-8e4b-dc9b7e7c982b/ReportSection?ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666&filter=Cluster%2FClusterId%20eq '<CLUSTER_ID>'"
            - name: MigrationConfig__NtbsEnvironment
              value: "PheDev"
            - name: Sentry__Environment
              value: phe-dev
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
            - name: EnvironmentDescription__ContainsLiveData
              value: "false"
            - name: EnvironmentDescription__IsLiveSystem
              value: "false"
            - name: EnvironmentDescription__DisplayName
              value: "development"
            - name: EnvironmentDescription__EnvironmentName
              value: "phe-dev"
            - name: ScheduledJobsConfig__UserSyncCron
              value: "00 21 * * *"
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-dev
  labels:
    app: ntbs-dev
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-dev
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-dev
spec:
  host: ntbs-dev.apps.ocp-por.unix.phe.gov.uk
  path: /
  to:
    kind: Service
    name: ntbs-dev
