# To be deployed on PHE Kubernetes and run against databases on the "dev" box DEVCOL01
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntbs-dev
  template:
    metadata:
      labels:
        app: ntbs-dev
    spec:
      containers:
        - name: ntbs-dev
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:dev"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: dev-connection-strings
                  key: reporting
            - name: Hangfire__WorkerCount
              value: "3"
            - name: HttpBasicAuth__Enabled
              value: "true"
            - name: HttpBasicAuth__Username
              valueFrom:
                secretKeyRef:
                  name: dev-http-basic-auth-credentials
                  key: username
            - name: HttpBasicAuth__Password
              valueFrom:
                secretKeyRef:
                  name: dev-http-basic-auth-credentials
                  key: password
            - name: ExternalLinks__ReportingOverview
              value: ""
            - name: MigrationConfig__TablePrefix
              value: "PheDev"
            - name: AppConfig__AuditingEnabled
              value: "true"
            - name: ScheduledJobsConfig__UserSyncEnabled
              value: "false"
            - name: ScheduledJobsConfig__MarkImportedNotificationsAsImportedEnabled
              value: "true"
            - name: Sentry__Environment
              value: phe-dev
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-dev
  labels:
    app: ntbs-dev
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-dev
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-dev
spec:
  host: ntbs-dev.apps.ocp-por.unix.phe.gov.uk
  path: /
  to:
    kind: Service
    name: ntbs-dev
