# To be deployed on PHE Kubernetes
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ntbs-live
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ntbs-live
    spec:
      containers:
        - name: ntbs-live
          image: "ntbscontainerregistry.azurecr.io/ntbs-service"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: live-db-connection-string
                  key: connectionString
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: live-audit-db-connection-string
                  key: connectionString
#             - name: ConnectionStrings__ltbr
#               valueFrom:
#                 secretKeyRef:
#                   name: lgeacy-and-migration-connection-strings
#                   key: ltbr
#             - name: ConnectionStrings__ets
#               valueFrom:
#                 secretKeyRef:
#                   name: lgeacy-and-migration-connection-strings
#                   key: ets
#             - name: ConnectionStrings__migration
#               valueFrom:
#                 secretKeyRef:
#                   name: lgeacy-and-migration-connection-strings
#                   key: migration
            - name: AdfsOptions__UseDummyAuth
              value: "true"
#            - name: LdapConnectionSettings__Password
#              valueFrom:
#                secretKeyRef:
#                  name: development-ad-sync-credentials
#                  key: password
            - name: ExternalLinks__ReportingUri
              value: ""
      imagePullSecrets:
        - name: registery-password
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-live
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-live