# To be deployed on PHE Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ntbs-live
  template:
    metadata:
      labels:
        app: ntbs-live
    spec:
      # Attempts to schedule the second replica's pod on a different node than the first
      # as a way to guard against unexpected node failures
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ntbs-live
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ntbs-live
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:live"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: AdfsOptions__AdfsUrl
              value: "https://fs.caduceus.phe.gov.uk"
            - name: AdfsOptions__Wtrealm
              value: "https://ntbs.phe.nhs.uk/"
            - name: AzureAdOptions__ClientId
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientId
            - name: AzureAdOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientSecret
            - name: AzureAdOptions__Authority
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: authority
            - name: AzureAdOptions__Enabled
              value: "true"
            - name: AppConfig__AuditingEnabled
              value: "true"
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: reporting
            - name: ExternalLinks__ReportingOverview
              value: ""
            - name: HttpBasicAuth__Enabled
              value: "false"
            - name: HttpBasicAuth__Username
              valueFrom:
                secretKeyRef:
                  name: live-http-basic-auth-credentials
                  key: username
            - name: HttpBasicAuth__Password
              valueFrom:
                secretKeyRef:
                  name: live-http-basic-auth-credentials
                  key: password
            - name: LdapSettings__AdAddressName
              value: ""
            - name: LdapSettings__Port
              value: "389"
            - name: LdapSettings__UserIdentifier
              value: "" # intentionally empty so the app's service account gets used for authentication
            - name: LdapSettings__Password
              value: "" # intentionally empty so the app's service account gets used for authentication
            - name: LdapSettings__BaseDomain
              value: "DC=phe,DC=gov,DC=uk"
            - name: MigrationConfig__TablePrefix
              value: "MigrationTrial4"
            - name: ScheduledJobsConfig__UserSyncEnabled
              value: "false"
            - name: ScheduledJobsConfig__MarkImportedNotificationsAsImportedEnabled
              value: "false"
            - name: ExternalLinks__ReportingOverview
              value: "https://app.powerbi.com/Redirect?action=OpenApp&appId=70e1af43-d5ca-48f8-b8c3-e146fc470fb7&ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666"
            - name: Sentry__Environment
              value: live
            - name: KRB5_CLIENT_KTNAME
              value: /krbtab/keytab
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
          volumeMounts:
            - mountPath: /krbtab
              name: krb-tab
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-live-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-live
  labels:
    app: ntbs-live
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-live
---
# Real live route, connected to ntbs.phe.nhs.uk
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-live-tls-n3
spec:
  host: ntbs.phe.nhs.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: coming-soon
  port:
    targetPort: 8080
  wildcardPolicy: None
---
# Temp route that allows us to access the app whilst it's not yet available on the real routes
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-live-hidden
spec:
  host: ntbs-live-hidden.apps.ocp-por.unix.phe.gov.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ntbs-live
---
# Disruption budget makes sure that manual node drains done by k8s admin
# wait for the app to have a pod running on another node before killing it
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ntbs-live-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ntbs-live
