# To be deployed on PHE Kubernetes
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ntbs-live
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ntbs-live
      annotations:
        image.openshift.io/triggers: >-
          [{"from":{"kind":"ImageStreamTag","name":"krb5-authenticator:latest","namespace":"krb5-authenticator"},"fieldPath":"spec.template.spec.containers[?(@.name==\"krb5-authenticator\")].image"}]
    spec:
      containers:
        - name: ntbs-live
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:live"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: migration
            - name: HttpBasicAuth__Enabled
              value: "true"
            - name: HttpBasicAuth__Username
              valueFrom:
                secretKeyRef:
                  name: live-http-basic-auth-credentials
                  key: username
            - name: HttpBasicAuth__Password
              valueFrom:
                secretKeyRef:
                  name: live-http-basic-auth-credentials
                  key: password
#            - name: LdapConnectionSettings__Password
#              valueFrom:
#                secretKeyRef:
#                  name: development-ad-sync-credentials
#                  key: password
            - name: ExternalLinks__ReportingUri
              value: ""
            - name: ReferenceLabResultsConfig__MockOutSpecimenMatching
              value: "true"
            - name: ClusterMatchingConfig__MockOutClusterMatching
              value: "true"
            - name: MigrationConfig__DateRangeJobIntervalInMonths
              value: "2"
            - name: MigrationConfig__TablePrefix
              value: "migrationTrial3"
            - name: AppConfig__AuditingEnabled
              value: "false"
            - name: ScheduledJobsConfig__UserSyncEnabled
              value: "false"
            - name: ScheduledJobsConfig__DrugResistanceProfileUpdateEnabled
              value: "false"
            - name: ScheduledJobsConfig__UnmatchedLabResultAlertsEnabled
              value: "false"
            - name: ScheduledJobsConfig__DataQualityAlertsEnabled
              value: "false"
            - name: ScheduledJobsConfig__NotificationClusterUpdateEnabled
              value: "false"
            - name: Sentry__Environment
              value: live
            - name: KRB5CCNAME
              value: /krb5cc/cc
          volumeMounts:
            - mountPath: /krb5cc
              name: krb5cc
        - name: krb5-authenticator
          image: krb5-authenticator/krb5-authenticator:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /krb5cc
              name: krb5cc
            - mountPath: /run/secrets/keytab
              name: krb-tab
              readOnly: true
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb5cc
          emptyDir: {}
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-live-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-live
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-live
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-live	
spec:
  rules:
    - host: ntbs-live.ocpappcol01.unix.phe.gov.uk
      http:
        paths:
          - backend:
              serviceName: ntbs-live
              servicePort: 80
            path: /