apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-load-test
spec:
  selector:
    matchLabels:
      app: ntbs-load-test
  replicas: 2
  template:
    metadata:
      labels:
        app: ntbs-load-test
    spec:
      containers:
      - name: ntbs-load-test
        image: "ntbscontainerregistry.azurecr.io/ntbs-service:load-test"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
          - name: ConnectionStrings__ntbsContext
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: appDb
          - name: ConnectionStrings__ntbsMigratorContext
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: appDbMigrator
          - name: ConnectionStrings__keysContext
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: appDb
          - name: ConnectionStrings__auditContext
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: auditDb
          - name: ConnectionStrings__reporting
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: reportingDb
          - name: ConnectionStrings__specimenMatching
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: specimenMatchingDb
          - name: ConnectionStrings__migration
            valueFrom:
              secretKeyRef:
                name: load-test-connection-strings
                key: migrationDb
          - name: AdOptions__BaseUserGroup
            value: "Global.NIS.NTBS"
          - name: AdOptions__AdminUserGroup
            value: "Global.NIS.NTBS.Admin"
          - name: AdOptions__NationalTeamAdGroup
            value: "Global.NIS.NTBS.NTS"
          - name: AdOptions__ServiceGroupAdPrefix
            value: "Global.NIS.NTBS.Service"
          - name: AdOptions__UseDummyAuth
            value: "true"
          - name: MigrationConfig__TablePrefix
            value: "LoadTest"
          - name: Sentry__Environment
            value: "load-test"
          - name: ScheduledJobsConfig__UserSyncEnabled
            value: "false"
          - name: EnvironmentDescription__EnvironmentName
            value: "azure-load-test"
      imagePullSecrets:
      - name: registry-password
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-load-test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-load-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-load-test
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  tls:
    - hosts:
      - ntbs-load-test.e32846b1ddf0432eb63f.northeurope.aksapp.io
      secretName: phe-ntbs-load-test-tls
  rules:
  - host: ntbs-load-test.e32846b1ddf0432eb63f.northeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ntbs-load-test
          servicePort: 80
        path: /
