apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ntbs-research
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ntbs-research
    spec:
      containers:
        - name: ntbs-research
          image: "ntbscontainerregistry.azurecr.io/ntbs-service"
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: research-db-connection-string
                  key: connectionString
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: research-audit-db-connection-string
                  key: connectionString
          - name: ConnectionStrings__ltbr
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: ltbr
          - name: ConnectionStrings__ets
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: ets
          - name: ConnectionStrings__migration
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: migration
            - name: AdfsOptions__Wtrealm
              value: "https://ntbs-research.da0c702c3b574e3185f6.uksouth.aksapp.io"
      imagePullSecrets:
        - name: registery-password
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-research
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: ntbs-research
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-research
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: research-basic-auth
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ntbsBeta"
spec:
  tls:
    - hosts:
        - ntbs-research.da0c702c3b574e3185f6.uksouth.aksapp.io
      secretName: phe-ntbs-research-tls
  rules:
    - host: ntbs-research.da0c702c3b574e3185f6.uksouth.aksapp.io
      http:
        paths:
          - backend:
              serviceName: ntbs-research
              servicePort: 80
            path: /
