# To be deployed on PHE Kubernetes and run against the test databases
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntbs-test
  template:
    metadata:
      labels:
        app: ntbs-test
    spec:
      containers:
        - name: ntbs-test
          image: "ghcr.io/publichealthengland/ntbs-service:test-phe"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
            - name: AzureAdOptions__Enabled
              value: "true"
            - name: AzureAdOptions__ClientId
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientId
            - name: AzureAdOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientSecret
            - name: AzureAdOptions__Authority
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: authority
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: test-connection-strings
                  key: reporting
            - name: ExternalLinks__ReportingOverview
              value: "https://app.powerbi.com/Redirect?action=OpenApp&appId=c5bd30d4-b135-4e44-81a4-00d61f360721&ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666"
            - name: MigrationConfig__NtbsEnvironment
              value: "Test"
            - name: Sentry__Environment
              value: phe-test
            - name: Splunk__Host
              value: "https://http-inputs-nhsttpreprod.splunkcloud.com"
            - name: Splunk__Token
              valueFrom:
                secretKeyRef:
                  name: splunk
                  key: test-token
            - name: Splunk__UriPath
              value: "services/collector/event"
            - name: Splunk__Index
              value: "ntbs_dotnet_test"
            - name: KRB5_CLIENT_KTNAME
              value: /krbtab/keytab
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
            - name: EnvironmentDescription__ContainsLiveData
              value: "false"
            - name: EnvironmentDescription__IsLiveSystem
              value: "false"
            - name: EnvironmentDescription__DisplayName
              value: "test"
            - name: EnvironmentDescription__EnvironmentName
              value: "phe-test"
            - name: ScheduledJobsConfig__UserSyncCron
              value: "30 21 * * *"
          volumeMounts:
            - mountPath: /krbtab
              name: krb-tab
      imagePullSecrets:
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-test-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-test
  labels:
    app: ntbs-test
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-test
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-test
spec:
  host: ntbs-test.apps.ocp-por.unix.phe.gov.uk
  path: /
  to:
    kind: Service
    name: ntbs-test
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
