# To be deployed on PHE Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ntbs-uat
  template:
    metadata:
      labels:
        app: ntbs-uat
    spec:
      # Attempts to schedule the second replica's pod on a different node than the first
      # as a way to guard against unexpected node failures
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ntbs-uat
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ntbs-uat
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:uat"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: AdfsUrl
              value: "https://fs.phe.gov.uk"
            - name: AdfsOptions__Wtrealm
              value: "https://ntbs-uat.phe.gov.uk/"
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: reporting
            - name: HttpBasicAuth__Enabled
              value: "false"
            - name: HttpBasicAuth__Username
              valueFrom:
                secretKeyRef:
                  name: uat-http-basic-auth-credentials
                  key: username
            - name: HttpBasicAuth__Password
              valueFrom:
                secretKeyRef:
                  name: uat-http-basic-auth-credentials
                  key: password
#            - name: LdapConnectionSettings__Password
#              valueFrom:
#                secretKeyRef:
#                  name: development-ad-sync-credentials
#                  key: password
            - name: ExternalLinks__ReportingUri
              value: ""
            - name: MigrationConfig__TablePrefix
              value: "UatPheMigration"
            - name: ScheduledJobsConfig__UserSyncEnabled
              value: "false"
            - name: ScheduledJobsConfig__MarkImportedNotificationsAsImportedEnabled
              value: "false"
            - name: Sentry__Environment
              value: uat-phe
            - name: KRB5_CLIENT_KTNAME
              value: /krbtab/keytab
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
          volumeMounts:
            - mountPath: /krbtab
              name: krb-tab
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-uat-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-uat
  labels:
    app: ntbs-uat
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-uat
---
# Real UAT route, connected to ntbs-uat.phe.nhs.uk
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-uat-tls-n3
spec:
  host: ntbs-uat.phe.nhs.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: coming-soon
  port:
    targetPort: 8080
  wildcardPolicy: None
---
# Temporary route, allowing us access to UAT whilst it's not amiable on final url
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-uat-hidden
spec:
  host: ntbs-uat-hidden.apps.ocp-por.unix.phe.gov.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ntbs-uat
---
# Disruption budget makes sure that manual node drains done by k8s admin
# wait for the app to have a pod running on another node before killing it
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ntbs-uat-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ntbs-uat
