# To be deployed on PHE Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ntbs-uat
  template:
    metadata:
      labels:
        app: ntbs-uat
      annotations:
        image.openshift.io/triggers: >-
          [{"from":{"kind":"ImageStreamTag","name":"krb5-authenticator:latest","namespace":"krb5-authenticator"},"fieldPath":"spec.template.spec.containers[?(@.name==\"krb5-authenticator\")].image"}]
    spec:
      # Attempts to schedule the second replica's pod on a different node than the first
      # as a way to guard against unexpected node failures
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ntbs-uat
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ntbs-uat
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:uat"
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: uat-connection-strings
                  key: reporting
            - name: HttpBasicAuth__Enabled
              value: "true"
            - name: HttpBasicAuth__Username
              valueFrom:
                secretKeyRef:
                  name: uat-http-basic-auth-credentials
                  key: username
            - name: HttpBasicAuth__Password
              valueFrom:
                secretKeyRef:
                  name: uat-http-basic-auth-credentials
                  key: password
#            - name: LdapConnectionSettings__Password
#              valueFrom:
#                secretKeyRef:
#                  name: development-ad-sync-credentials
#                  key: password
            - name: ExternalLinks__ReportingUri
              value: ""
            - name: MigrationConfig__DateRangeJobIntervalInMonths
              value: "2"
            - name: MigrationConfig__TablePrefix
              value: "UatPheMigration"
            - name: AppConfig__AuditingEnabled
              value: "false"
            - name: ScheduledJobsConfig__UserSyncEnabled
              value: "false"
            - name: ScheduledJobsConfig__MarkImportedNotificationsAsImportedEnabled
              value: "false"
            - name: Sentry__Environment
              value: uat-phe
            - name: KRB5_CLIENT_KTNAME
              value: /krbtab/keytab
          volumeMounts:
            - mountPath: /krbtab
              name: krb-tab
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-uat-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-uat
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-uat
---
# Real UAT route, connected to ntbs-uat.phe.nhs.uk
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-uat	
spec:
  rules:
    - host: ntbs-uat.apps.ocp-por.unix.phe.gov.uk
      http:
        paths:
          - backend:
              serviceName: coming-soon
              servicePort: 80
            path: /
---
# Temporary route, allowing us access to UAT whilst it's not amiable on final url
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-uat-hidden
spec:
  rules:
    - host: ntbs-uat-hidden.apps.ocp-por.unix.phe.gov.uk
      http:
        paths:
          - backend:
              serviceName: ntbs-uat
              servicePort: 80
            path: /
---
# Disruption budget makes sure that manual node drains done by k8s admin
# wait for the app to have a pod running on another node before killing it
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ntbs-uat-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ntbs-uat
