apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ntbs-uat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ntbs-uat
    spec:
      containers:
      - name: ntbs-uat
        image: "ntbscontainerregistry.azurecr.io/ntbs-service"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionStrings__ntbsContext
            valueFrom:
              secretKeyRef:
                name: uat-db-connection-string
                key: connectionString
          - name: ConnectionStrings__auditContext
            valueFrom:
              secretKeyRef:
                name: uat-audit-db-connection-string
                key: connectionString
          - name: ConnectionStrings__reporting
            valueFrom:
              secretKeyRef:
                name: uat-reporting-db-connection-string
                key: connectionString
          - name: ConnectionStrings__specimenMatching
            valueFrom:
              secretKeyRef:
                name: test-specimen-matching-connection-string
                key: connectionString
          - name: ConnectionStrings__ltbr   
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: ltbr
          - name: ConnectionStrings__ets
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: ets
          - name: ConnectionStrings__migration
            valueFrom:
              secretKeyRef:
                name: lgeacy-and-migration-connection-strings
                key: migration
          - name: AdfsOptions__Wtrealm
            value: "https://ntbs-uat.da0c702c3b574e3185f6.uksouth.aksapp.io"
          - name: LdapConnectionSettings__Password
            valueFrom:
              secretKeyRef:
                name: development-ad-sync-credentials
                key: password
          - name: ExternalLinks__ReportingUri
            value: ""
          - name: Environment_Name
            value: "Uat"
      imagePullSecrets:
      - name: registery-password
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-uat
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-uat
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-uat
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  tls:
    - hosts:
      - ntbs-uat.da0c702c3b574e3185f6.uksouth.aksapp.io
      secretName: phe-ntbs-uat-tls
  rules:
  - host: ntbs-uat.da0c702c3b574e3185f6.uksouth.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ntbs-uat
          servicePort: 80
        path: /