apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ntbs-publish-database
  namespace: ntbs-build
spec:
  params:
    - default: 'yes'
      description: Do you want to deploy the migration database?
      name: deploy-migration
      type: string
    - default: 'yes'
      description: Do you want to deploy the specimen-matching database?
      name: deploy-specimen-matching
      type: string
    - default: 'yes'
      description: Do you want to deploy the reporting database?
      name: deploy-reporting
      type: string
    - default: uat
      description: The environment you are deploying to (uat or live)
      name: environment
      type: string
    - default: live
      description: The branch to deploy
      name: branch
      type: string
  tasks:
    - name: git-clone-migration
      params:
        - name: url
          value: 'git@github.com:publichealthengland/ntbs-data-migration.git'
        - name: revision
          value: $(params.branch)
        - name: submodules
          value: 'false'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: data-migration
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(params.deploy-migration)
          operator: in
          values:
            - 'yes'
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-directory
    - name: publish-migration
      params:
        - name: checkout_directory
          value: data-migration
        - name: dacpac_directory
          value: build
        - name: dacpac_file_name
          value: ntbs-data-migration.dacpac
        - name: config_map
          value: $(params.environment)
        - name: publish_profile_key
          value: databases.migration-publish-profile
        - name: reference_dacpacs_path
          value: ntbs-data-migration/data
        - name: sql-user-secret
          value: $(params.environment)-sql-keytab
      runAfter:
        - git-clone-migration
      taskRef:
        kind: Task
        name: publish-dacpac
      workspaces:
        - name: input
          workspace: shared-workspace
    - name: git-clone-specimen-matching
      params:
        - name: url
          value: 'git@github.com:publichealthengland/ntbs-specimen-matching.git'
        - name: revision
          value: $(params.branch)
        - name: submodules
          value: 'false'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: specimen-matching
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(params.deploy-specimen-matching)
          operator: in
          values:
            - 'yes'
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-directory
    - name: publish-specimen-matching
      params:
        - name: checkout_directory
          value: specimen-matching
        - name: dacpac_directory
          value: build
        - name: dacpac_file_name
          value: ntbs-specimen-matching.dacpac
        - name: config_map
          value: $(params.environment)
        - name: publish_profile_key
          value: databases.specimen-matching-publish-profile
        - name: reference_dacpacs_path
          value: data/DACPAC
        - name: sql-user-secret
          value: $(params.environment)-sql-keytab
      runAfter:
        - git-clone-specimen-matching
      taskRef:
        kind: Task
        name: publish-dacpac
      workspaces:
        - name: input
          workspace: shared-workspace
    - name: git-clone-reporting
      params:
        - name: url
          value: 'git@github.com:publichealthengland/ntbs-reporting.git'
        - name: revision
          value: $(params.branch)
        - name: submodules
          value: 'false'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
        - name: subdirectory
          value: reporting
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(params.deploy-reporting)
          operator: in
          values:
            - 'yes'
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: ssh-directory
          workspace: ssh-directory
    - name: publish-reporting
      params:
        - name: checkout_directory
          value: reporting
        - name: dacpac_directory
          value: build
        - name: dacpac_file_name
          value: ntbs-reporting.dacpac
        - name: config_map
          value: $(params.environment)
        - name: publish_profile_key
          value: databases.reporting-publish-profile
        - name: reference_dacpacs_path
          value: data/DACPAC
        - name: sql-user-secret
          value: $(params.environment)-sql-keytab
      runAfter:
        - git-clone-reporting
      taskRef:
        kind: Task
        name: publish-dacpac
      workspaces:
        - name: input
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
    - name: ssh-directory
