# Temporarily-unavailable page app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporarily-unavailable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporarily-unavailable
  template:
    metadata:
      labels:
        app: temporarily-unavailable
    spec:
      containers:
        - name: temporarily-unavailable-app
          image: "ntbscontainerregistry.azurecr.io/temporarily-unavailable"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: App__ReportsUrl
              value:
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
---
apiVersion: v1
kind: Service
metadata:
  name: temporarily-unavailable
  labels:
    app: temporarily-unavailable
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: temporarily-unavailable
