apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-int
  namespace: default
spec:
  dnsNames:
    - ntbs-int.61b431d7ea3041e89733.uksouth.aksapp.io
  secretName: phe-ntbs-int-tls
  issuerRef:
    name: int-cluster-issuer
    kind: ClusterIssuer