apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-int
  namespace: default
spec:
  dnsNames:
    - ntbs-int.e32846b1ddf0432eb63f.northeurope.aksapp.io
  secretName: phe-ntbs-int-tls
  issuerRef:
    name: int-cluster-issuer
    kind: ClusterIssuer