apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: test-cluster-issuer
spec:
  acme:
    email: team-ntbs@softwire.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: phe-ntbs-test-tls
    solvers:
    - http01:
       ingress:
         class: addon-http-application-routing