apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-test
  namespace: default
spec:
  dnsNames:
    - ntbs-test.61b431d7ea3041e89733.uksouth.aksapp.io
  secretName: phe-ntbs-test-tls
  issuerRef:
    name: test-cluster-issuer
    kind: ClusterIssuer