apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-test
  namespace: default
spec:
  dnsNames:
    - ntbs-test.e32846b1ddf0432eb63f.northeurope.aksapp.io
  secretName: phe-ntbs-test-tls
  issuerRef:
    name: test-cluster-issuer
    kind: ClusterIssuer