apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-training
  namespace: default
spec:
  dnsNames:
    - ntbs-training.e32846b1ddf0432eb63f.northeurope.aksapp.io
  secretName: phe-ntbs-training-tls
  issuerRef:
    name: training-cluster-issuer
    kind: ClusterIssuer