apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ntbs-uat
  namespace: default
spec:
  dnsNames:
    - ntbs-uat.e32846b1ddf0432eb63f.northeurope.aksapp.io
  secretName: phe-ntbs-uat-tls
  issuerRef:
    name: uat-cluster-issuer
    kind: ClusterIssuer