// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ntbs_service.DataAccess;

namespace ntbs_service.Migrations
{
    [DbContext(typeof(NtbsContext))]
    [Migration("20210629101706_InitialMigrationsSquashed_prep")]
    partial class InitialMigrationsSquashed_prep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

#pragma warning restore 612, 618
        }
    }
}
