kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cleanup-runs-cron
  namespace: ntbs-build
spec:
  schedule: 0 0 * * *
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notify-event-listener
              image: busybox
              args:
                - wget
                - '--spider'
                - 'el-tekton-cleaner-listener.ntbs-build.svc.cluster.local:8080'
              imagePullPolicy: Always
          restartPolicy: Never
