apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-routes-file
  namespace: ntbs-build
spec:
  params:
    - description: The routes to deploy
      name: route_file
      type: string
  steps:
    - image: 'image-registry.openshift-image-registry.svc:5000/ntbs-build/ntbs-image-stream:openshift-cli'
      name: apply
      resources: {}
      script: >
        route_file=$(inputs.params.route_file)

        echo "Applying $route_file file"

        oc project ntbs

        oc apply -f ntbs-service/deployments/$route_file

        echo "Finished applying $route_file file"
      workingDir: /workspace/output
  workspaces:
    - name: output
