name: Backup live container

on:
  push:
    tags:
      - Release-*

jobs:
  backup-live-container-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get the live release tag
        id: get_tag
        run: echo ::set-output name=BRANCH_TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and publish backup
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ntbs-backups
          registry: ntbsbackups.azurecr.io
          username: ${{ secrets.BACKUP_DOCKER_USERNAME }}
          password: ${{ secrets.BACKUP_DOCKER_PASSWORD }}
          # auth token based on https://sentry.io/settings/phe-ntbs/developer-settings/jenkins-build-40d229/
          build_extra_args: ${{ format('--build-arg RELEASE={0} --build-arg SENTRY_AUTH_TOKEN={1}', steps.get_tag.outputs.BRANCH_TAG, secrets.SENTRY_AUTH_TOKEN) }}
          image_tag: ${{ steps.get_tag.outputs.BRANCH_TAG }}
