name: master test and publish to int

on:
  push:
    branches: [ github-actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set build number
      run: echo '::set-env name=NTBS_BUILD::build-${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:6}'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
#     - name: Run unit tests
#       working-directory: ntbs-service-unit-tests
#       run: dotnet test
#     - name: Run unit tests (EF)
#       working-directory: EFAuditer-tests
#       run: dotnet test
#     - name: Run integration tets
#       working-directory: ntbs-integration-tests
#       run: dotnet test
    # TODO ? run ui tests
    
    
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: ntbs_app
        registry: ntbscontainerregistry.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ntbs-service
        build_args: RELEASE=${NTBS_BUILD}, SENTRY_AUTH_TOKEN=${secret.SENTRY_AUTH_TOKEN}
        image_tag: ${NTBS_BUILD}
      
      
